events {}

http {
    server {
        listen 80;

        # Auth servis yönlendirmesi
        location /api/auth/ {
            proxy_pass http://auth-service:8000/api/auth/;
        }

        # Flask ana uygulamasına yönlendirme
        location /api/ {
            proxy_pass http://core-service:5000/api/;
        }
    }
}