events {}

http {
    # Bellekte 'auth_limit' adında bir alan ayır, saniyede 1 isteğe izin ver
    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=1r/s;

    server {
        listen 80;

        # Auth servisine rate limit uyguluyoruz (burst=5 ile anlık 5 isteği tolere eder)
        location /api/auth/ {
            limit_req zone=auth_limit burst=5 nodelay;
            proxy_pass http://auth-service:8000/api/auth/;
        }

        # Flask ana uygulamasına yönlendirme (limit yok)
        location /api/ {
            proxy_pass http://core-service:5000/api/;
        }
    }
}